name: beetlefinder

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.0.1

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: true
